"""Minimal pyarrow surface, covering only what labmon calls.

Hand-written for the same reason as the other stubs here: pyarrow ships
no type information, and without this basedpyright reports every table
operation as an unknown type. Scoped deliberately — adding a signature
when a new call needs one is cheaper than tracking the whole library.
"""

from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Any, Self

class DataType:
    def __eq__(self, other: object) -> bool: ...

class TimestampType(DataType):
    @property
    def tz(self) -> str | None: ...
    @property
    def unit(self) -> str: ...

class Field:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> DataType: ...
    @property
    def metadata(self) -> dict[bytes, bytes] | None: ...
    def with_metadata(self, metadata: Mapping[bytes, bytes]) -> Field: ...

class Schema:
    @property
    def names(self) -> list[str]: ...
    @property
    def metadata(self) -> dict[bytes, bytes] | None: ...
    def field(self, name: str | int) -> Field: ...
    def with_metadata(self, metadata: Mapping[bytes, bytes]) -> Schema: ...
    def set(self, index: int, field: Field) -> Schema: ...
    def __iter__(self) -> Iterator[Field]: ...
    def __len__(self) -> int: ...

class Scalar: ...

class Array:
    @property
    def type(self) -> DataType: ...
    def cast(
        self, target_type: DataType, safe: bool = ..., options: object = ...
    ) -> Array: ...
    def dictionary_encode(self) -> Array: ...
    def to_pylist(self) -> list[object]: ...
    def __len__(self) -> int: ...

class ChunkedArray:
    @property
    def type(self) -> DataType: ...
    def cast(
        self, target_type: DataType, safe: bool = ..., options: object = ...
    ) -> ChunkedArray: ...
    def to_pylist(self) -> list[object]: ...
    def __len__(self) -> int: ...

class Table:
    @property
    def num_rows(self) -> int: ...
    @property
    def column_names(self) -> list[str]: ...
    @property
    def schema(self) -> Schema: ...
    def column(self, name: str | int) -> ChunkedArray: ...
    def select(self, columns: Sequence[str]) -> Table: ...
    def slice(self, offset: int = ..., length: int | None = ...) -> Table: ...
    def filter(self, mask: ChunkedArray | Array) -> Table: ...
    def take(self, indices: ChunkedArray | Array) -> Table: ...
    def cast(self, target_schema: Schema) -> Table: ...
    def to_pydict(self) -> dict[str, list[object]]: ...
    def sort_by(self, sorting: Sequence[tuple[str, str]]) -> Table: ...
    def append_column(
        self, field_: str | Field, column: Array | ChunkedArray
    ) -> Table: ...
    @staticmethod
    def from_arrays(
        arrays: Sequence[ChunkedArray | Array], names: Sequence[str]
    ) -> Table: ...

class RecordBatchFileWriter:
    def write_table(self, table: Table) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...

def array(obj: Iterable[Any], type: DataType | None = ...) -> Array: ...
def chunked_array(
    arrays: Sequence[Array], type: DataType | None = ...
) -> ChunkedArray: ...
def nulls(size: int, type: DataType | None = ...) -> Array: ...
def scalar(value: object, type: DataType | None = ...) -> Scalar: ...
def table(data: Mapping[str, Array | ChunkedArray]) -> Table: ...
def schema(fields: Iterable[Field]) -> Schema: ...
def concat_tables(tables: Sequence[Table]) -> Table: ...
def timestamp(unit: str, tz: str | None = ...) -> TimestampType: ...
def dictionary(index_type: DataType, value_type: DataType) -> DataType: ...
def int32() -> DataType: ...
def int64() -> DataType: ...
def string() -> DataType: ...
def float64() -> DataType: ...
