"""The handful of pyarrow.compute kernels labmon uses."""

from collections.abc import Sequence

from pyarrow import Array, ChunkedArray, Scalar, Table

def assume_timezone(timestamps: ChunkedArray, timezone: str) -> ChunkedArray: ...
def sort_indices(input: Table, sort_keys: Sequence[tuple[str, str]] = ...) -> Array: ...
def is_null(values: ChunkedArray) -> ChunkedArray: ...
def equal(left: ChunkedArray, right: Scalar) -> ChunkedArray: ...
