"""Minimal local stub for the parts of pint labmon actually uses.

pint ships a py.typed marker, but its own annotations resolve to
Unknown under basedpyright's strictest preset (Quantity is a generic
alias whose members come back unparameterized), so the real package
can't satisfy this project's zero-warning gate. Same situation, and
same fix, as the influxdb_client_3 stub next door.
"""

class Unit:
    def __mul__(self, other: Unit | Quantity | float, /) -> Quantity: ...
    def __rmul__(self, other: float, /) -> Quantity: ...
    def __truediv__(self, other: Unit | Quantity | float, /) -> Quantity: ...
    def __format__(self, format_spec: str, /) -> str: ...

class Quantity:
    @property
    def magnitude(self) -> float: ...
    @property
    def units(self) -> Unit: ...
    def to(self, other: Unit | str, /) -> Quantity: ...
    def to_base_units(self) -> Quantity: ...
    def __mul__(self, other: Unit | Quantity | float, /) -> Quantity: ...
    def __rmul__(self, other: float, /) -> Quantity: ...
    def __truediv__(self, other: Unit | Quantity | float, /) -> Quantity: ...
    def __add__(self, other: Quantity, /) -> Quantity: ...
    def __sub__(self, other: Quantity, /) -> Quantity: ...

class UnitRegistry:
    def __init__(self) -> None: ...
    def __call__(self, expression: str, /) -> Quantity: ...
    def __getattr__(self, name: str, /) -> Unit: ...

class PintError(Exception): ...
class UndefinedUnitError(PintError, AttributeError): ...
class OffsetUnitCalculusError(PintError, TypeError): ...
class DimensionalityError(PintError, ValueError): ...
