from collections.abc import Iterable
from datetime import datetime
from typing import Any

class Point:
    def __init__(self, measurement_name: str) -> None: ...
    def tag(self, key: str, value: Any) -> Point: ...
    def field(self, field: str, value: Any) -> Point: ...
    def time(
        self, time: datetime | str | int, write_precision: str = ...
    ) -> Point: ...

class InfluxDBClient3:
    def __init__(self, host: str, token: str, database: str) -> None: ...
    def write(self, record: Point | Iterable[Point]) -> None: ...
    def close(self) -> None: ...
