from collections.abc import Iterable
from datetime import datetime
from typing import Any

from pyarrow import Table

class Point:
    def __init__(self, measurement_name: str) -> None: ...
    def tag(self, key: str, value: Any) -> Point: ...
    def field(self, field: str, value: Any) -> Point: ...
    def time(self, time: datetime | str | int, write_precision: str = ...) -> Point: ...
    def to_line_protocol(
        self, precision: str | None = ..., tag_order: list[str] | None = ...
    ) -> str: ...

class InfluxDBClient3:
    def __init__(self, host: str, token: str, database: str, **kwargs: Any) -> None: ...
    def write(self, record: Point | Iterable[Point]) -> None: ...
    def query(
        self,
        query: str,
        language: str = ...,
        mode: str = ...,
        database: str | None = ...,
        **kwargs: Any,
    ) -> Table: ...
    def close(self) -> None: ...
